require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SennenPropertyManagement' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # target 'SennenPropertyManagementTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end


    # pod 'Firebase'
    # pod 'Firebase/Messaging'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.92.0' })
  post_install do |installer|
    flipper_post_install(installer)
    # based on https://stackoverflow.com/a/37289688/1983583
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end

# target 'SennenPropertyManagement-tvOS' do
#   # Pods for SennenPropertyManagement-tvOS

#   target 'SennenPropertyManagement-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
